import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useSelector } from 'react-redux'
import { setProfileData, selectProfile } from '../store/slices/profile'
import { wrapper } from '../store'

interface IHomeProps {
  resolvedUrl: string
}

const Home: NextPage<IHomeProps> = (props) => {
  const state = useSelector(selectProfile)

  const { resolvedUrl } = props
  console.log('>', resolvedUrl, state)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>1</div>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
  const { resolvedUrl } = context
  store.dispatch(setProfileData('My Server Name'))
  return {
    props: {
      resolvedUrl
    }
  }
})

export default Home
